apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
images:
  - name: nitinv1/app-env
    newTag: dev1

patchesStrategicMerge:
  - service-patch.yaml

patches:
  - target:
      kind: Deployment
    patch: |
      - op: add
         path: /spec/template/metadata/annotations/-
         value:
           link.argocd.argoproj.io/external-link: http://my-grafana.example.com/pre-generated-link
