apiVersion: v1
kind: Service
metadata:
  name: app-service
spec:
  selector:
    app: app
  ports:
    - protocol: TCP
      port: 8080              # External port (for Dev)
      targetPort: 5000         # Internal container port (your app)
  type: LoadBalancer
